# DeepScript - Schema v3
# Single Source of Truth for database structure
# Used by: CLAUDE.md, migration scripts, skills (/add, /export, /import)
# Updated: 2026-01-11

meta:
  version: 3
  updated: 2026-01-11
  description: Single source of truth for DeepScript database schema

# =============================================================================
# NODE TYPES
# =============================================================================

node_types:
  - Person
  - Organization    # with sub-labels
  - Family
  - Event

# Organization sub-labels
org_sublabels:
  - Forum           # Bilderberg, Trilateral, WEF, CFR
  - Company         # Corporate, holding
  - Bank            # Commercial + investment banks
  - CentralBank     # Fed, ECB, BoE
  - AssetManager    # BlackRock, Vanguard
  - PrivateEquity   # KKR, Carlyle, Blackstone
  - HedgeFund       # Bridgewater, Soros Fund
  - SWF             # Sovereign wealth funds
  - Government      # National executives
  - Party           # Political parties
  - Foundation      # Rockefeller, Gates, Open Society
  - ThinkTank       # Brookings, ISPI, Aspen
  - University      # Harvard, Oxford, Bocconi
  - Agency          # UN, IMF, NATO, EU Commission
  - Media           # News, TV, agency
  - Defense         # Lockheed Martin, RTX, BAE, Leonardo
  - Pharma          # Pfizer, Moderna, Roche, GSK
  - SportsClub      # PSG, Manchester City, AC Milan
  - Automaker       # BMW, Toyota, Stellantis, Geely
  - Airline         # Delta, Lufthansa, Emirates

# =============================================================================
# RELATIONSHIP TYPES
# =============================================================================

relationship_types:
  AFFILIATED_WITH:
    from: Person
    to: Organization
    properties:
      - role          # from affiliation_roles enum
      - from          # start year
      - to            # end year (null = current)
      - note          # details

  STAKE_IN:
    from: Organization
    to: Organization
    properties:
      - role          # from stake_roles enum
      - share         # percentage (0.0-1.0) or string "majority"
      - from
      - to
      - note

  MEMBER_OF:
    from: Person
    to: Family
    properties:
      - generation    # 1, 2, 3...
      - role          # from family_roles enum
      - note          # details

  RELATED_TO:
    from: Person
    to: Person
    properties:
      - type          # from person_relation_types enum
      - note          # details: "father", "rival", etc.

  PARTICIPATED_IN:
    from: Person
    to: Event
    properties:
      - role          # from event_participation_roles enum
      - note          # details

  INVOLVED_IN:
    from: Organization
    to: Event
    properties:
      - role          # from event_involvement_roles enum
      - note          # details

# =============================================================================
# DOCS PATH MAPPING (label -> folder in docs/)
# =============================================================================

docs_path_mapping:
  # Node types
  Person: persons
  Family: family
  Event: events
  # Organization sublabels
  Forum: forum
  Bank: bank
  CentralBank: central-bank
  AssetManager: asset-manager
  PrivateEquity: private-equity
  HedgeFund: hedge-fund
  SWF: swf
  Government: government
  Party: party
  Foundation: foundation
  ThinkTank: think-tank
  Company: company
  University: university
  Agency: agency
  Media: media
  Defense: defense
  Pharma: pharma
  SportsClub: sports-club
  Automaker: automaker
  Airline: airline

# =============================================================================
# ENUMS
# =============================================================================

enums:
  # ---------------------------------------------------------------------------
  # Person -> Person relation types
  # ---------------------------------------------------------------------------
  person_relation_types:
    - mentor        # direction: mentor -> mentee (note: "protege" for inverse)
    - associate     # note: "rival", "successor", "business partner"
    - spouse        # note: "ex", "partner"
    - family        # note: "father", "son", "brother", "sister"
    - friend

  # ---------------------------------------------------------------------------
  # Affiliation roles (Person -> Organization)
  # ---------------------------------------------------------------------------
  affiliation_roles:
    # Government (6 roles)
    - leader        # note: "President", "PM", "Governor", "Mayor", "King"
    - minister      # note: "Finance", "Defense", "Deputy", "Secretary of State"
    - legislator    # note: "Senator", "MP", "Speaker", "Representative"
    - judge         # note: "Chief Justice", "Constitutional Court"
    - diplomat      # note: "Ambassador to UN", "Consul Milan"
    - official      # note: "CIA Director", "Army Chief", "DG Treasury"

    # Company (8 roles)
    - founder       # note: "co-founder"
    - executive     # note: "CEO", "CFO", "COO", "CTO", "President"
    - chairman      # note: "Vice", "Executive Chairman"
    - board         # note: "Independent", "Non-executive"
    - partner       # note: "Managing Partner", "Senior Partner"
    - shareholder   # note: "51%", "Controlling", "Majority"
    - advisor       # note: "Senior", "Legal Counsel", "Consultant"
    - employee      # note: operational roles

    # Forum / ThinkTank (5 roles)
    # founder, chairman, board (reused from above)
    - fellow        # note: "Senior Fellow", "Trustee"
    - member        # note: "Participant", "Speaker"
    - steering      # steering committee

    # University (5 roles)
    # founder (reused)
    - president     # note: "Rector", "Chancellor", "Provost"
    - professor     # note: "Dean", "Associate", "Researcher"
    - alumni        # note: "Fellow", "MBA 1985"
    - trustee

    # Foundation (4 roles)
    # founder, chairman, trustee (reused)
    - grantee

    # Media (5 roles)
    # founder, chairman (reused)
    - owner
    - editor        # note: "Editor-in-Chief", "Columnist"
    - journalist    # note: "Anchor", "Correspondent"

    # Agency (5 roles)
    # leader, diplomat, official (reused)
    - commissioner  # note: "Representative", "Board Member"
    - asset         # note: intelligence asset (recruited, not employed)

    # WEF-specific
    - ygl           # Young Global Leader (post-2004)
    - glt           # Global Leader for Tomorrow (1993-2003)

  # ---------------------------------------------------------------------------
  # Stake roles (Organization -> Organization)
  # ---------------------------------------------------------------------------
  stake_roles:
    - stake         # use `share` for %, note: "majority", "minority", "controlling"
    - subsidiary    # note: "affiliate"
    - parent
    - joint-venture
    - partner       # strategic alliance

  # ---------------------------------------------------------------------------
  # Family roles (Person -> Family)
  # ---------------------------------------------------------------------------
  family_roles:
    - patriarch     # note: "matriarch"
    - heir          # note: "heir-apparent"
    - member
    - married-in    # note: "divorced-out"

  # ---------------------------------------------------------------------------
  # Event types
  # ---------------------------------------------------------------------------
  event_types:
    # Political
    - election      # note: "referendum", "impeachment"
    - coup          # note: "revolution", "assassination"

    # Economic
    - crisis        # note: "default", "bankruptcy"
    - bailout       # note: "restructuring"
    - deal          # note: "IPO", "merger", "acquisition"

    # Diplomatic
    - summit        # note: "conference", "annual-meeting"
    - treaty        # note: "alliance", "ceasefire"
    - sanctions
    - war

    # Institutional
    - reform        # note: "founding", "dissolution"

    # Scandal
    - scandal       # note: "investigation", "trial", "resignation"

  # ---------------------------------------------------------------------------
  # Event participation roles (Person -> Event)
  # ---------------------------------------------------------------------------
  event_participation_roles:
    - organizer     # note: "host", "initiator"
    - speaker       # note: "negotiator", "leader"
    - signatory
    - participant   # note: "attendee", "observer", "witness"
    - affected      # note: "winner", "loser", "victim", "beneficiary"

  # ---------------------------------------------------------------------------
  # Event involvement roles (Org -> Event)
  # ---------------------------------------------------------------------------
  event_involvement_roles:
    - organizer     # note: "host", "sponsor"
    - participant
    - signatory
    - affected      # note: "target", "victim", "beneficiary"
    - regulator
    - creditor      # note: "debtor"

  # ---------------------------------------------------------------------------
  # Sectors (for Company)
  # ---------------------------------------------------------------------------
  sectors:
    - finance       # note: "banking", "insurance", "asset-management"
    - tech          # note: "software", "hardware", "telecom", "semiconductor"
    - energy        # note: "oil-gas", "utilities", "renewables"
    - defense       # note: "aerospace", "military"
    - industry      # note: "automotive", "manufacturing"
    - consumer      # note: "retail", "luxury", "food-beverage"
    - healthcare    # note: "pharma", "biotech"
    - services      # note: "consulting", "legal", "real-estate"
    - media         # note: "entertainment"
    - transport     # note: "logistics", "shipping", "airlines"

  # ---------------------------------------------------------------------------
  # Media types (for Media sub-label)
  # ---------------------------------------------------------------------------
  media_types:
    - newspaper
    - tv            # note: "radio"
    - agency
    - digital
    - group         # media conglomerate

  # ---------------------------------------------------------------------------
  # Organization status
  # ---------------------------------------------------------------------------
  org_status:
    - active
    - defunct
    - merged

# =============================================================================
# TYPE MAPPING (yaml type value -> Neo4j sub-label)
# Used by import scripts to assign correct labels
# =============================================================================

type_mapping:
  # Forums
  forum: Forum
  network: Forum
  programma: Forum

  # Banks
  bank: Bank
  investment-bank: Bank
  central-bank: CentralBank
  centralbank: CentralBank

  # Asset management
  asset-manager: AssetManager
  assetmanager: AssetManager
  private-equity: PrivateEquity
  privateequity: PrivateEquity
  hedge-fund: HedgeFund
  hedgefund: HedgeFund
  sovereign-wealth-fund: SWF
  swf: SWF
  venture-capital: PrivateEquity

  # Corporations
  company: Company
  corporate: Company
  corporation: Company
  holding: Company
  tech: Company
  oil: Company
  telecom: Company
  retail: Company
  moto: Company
  assicurazioni: Company
  airline: Company
  infrastruttura: Company
  joint-venture: Company
  consulenza: Company

  # Defense
  defense: Defense
  difesa: Defense

  # Pharma
  pharma: Pharma
  farmaceutica: Pharma

  # Sports
  sports-club: SportsClub
  sportsclub: SportsClub
  club-sportivo: SportsClub

  # Automotive
  automaker: Automaker
  auto: Automaker
  automotive: Automaker

  # Airlines
  airline: Airline
  compagnia-aerea: Airline
  aviation: Airline

  # Government & Agencies
  government: Government
  governo: Government
  party: Party
  partito: Party
  agency: Agency
  agenzia: Agency
  organizzazione-internazionale: Agency
  istituzione-ue: Agency
  alleanza-militare: Agency
  istituzione-finanziaria: Agency
  cartello: Agency

  # Other orgs
  foundation: Foundation
  fondazione: Foundation
  think-tank: ThinkTank
  thinktank: ThinkTank
  advocacy: ThinkTank
  lobby: ThinkTank
  university: University
  universita: University
  media: Media
  testata: Media
  gruppo: Media
  broadcaster: Media

# =============================================================================
# ROLE MAPPING (legacy Italian roles -> English)
# =============================================================================

role_mapping:
  # Compound roles -> split into list
  ceo-fondatore: [founder, executive]
  fondatore-ceo: [founder, executive]
  fondatore-chairman: [founder, chairman]
  fondatore-direttore: [founder, executive]
  fondatore-rettore: [founder, president]
  fondatore-editore: [founder, editor]

  # Government roles
  capo-governo: leader
  capo-stato: leader
  ministro: minister
  vice-presidente: leader
  governatore: leader
  commissario: commissioner
  senatore: legislator
  ambasciatore: diplomat
  segretario-generale: leader
  consigliere: advisor

  # Corporate roles
  ceo: executive
  cfo: executive
  coo: executive
  cto: executive
  managing-director: executive
  chairman: chairman
  co-chairman: chairman
  vice-chairman: chairman
  executive-chairman: chairman
  presidente: executive
  board: board
  partner: partner
  senior-advisor: advisor
  advisor: advisor
  banchiere: employee
  proprietario: owner
  direttore: executive
  co-fondatore: founder
  fondatore: founder

  # Forum/ThinkTank roles
  steering: steering
  membro: member
  partecipante: member
  co-chair: chairman

  # WEF specific
  ygl: ygl
  glt: glt

  # University roles
  rettore: president
  docente: professor
  alumnus: alumni

  # Media roles
  editore: editor
  caporedattore: editor
  editorialista: editor
  inviato: journalist
  conduttore: journalist

  # Stakeholder roles (org -> org)
  holding: stake
  controllata: subsidiary
  cliente: partner

# =============================================================================
# FIELD MAPPING (Italian -> English)
# For legacy YAML files
# =============================================================================

field_mapping:
  # Person fields
  nato: born
  morto: died
  naz: nationality
  nota: note
  famiglia: family

  # Organization fields
  fondato: founded
  sede: headquarters
  tipo: type

  # Affiliation/Stake fields
  dal: from
  al: to
  ruolo: role
  percentuale: share
  persona: person
  org: org

  # Family fields
  origine: origin
  fondatore: founder
  settore_originario: sector
  generazioni: generations

  # Event fields
  anno: year
  mese: month
  luogo: location
  attori: actors
  risultato: outcome

# =============================================================================
# VALIDATION
# =============================================================================

validation:
  required_person_fields:
    - id
  required_org_fields:
    - id
  required_family_fields:
    - id
    - origin
  required_event_fields:
    - id
    - year
    - type
